add custom meter metric
idanto/node-metrics pull request #14
Opened 2017-01-11 15:49 UTC by meytal127

2017-01-15 11:46 UTC, idanto requested changes

2017-01-15 11:46 UTC, idanto commented on src/metrics.js
> +function resetCustomMetersMetrics() {
All of the other reset methods delete the metric so it will not appear in the next getMetrics request.

2017-01-15 11:46 UTC, idanto commented on src/metrics.js
> +module.exports.customMeterMetric = function (metricName) {
please change to addCustomMeterMetric

2017-01-15 11:46 UTC, idanto commented on src/metrics.js
> +var customMetersMetrics = new Set();
There is no way to get only the customMeterMetrics or the custom metrics in general, don't you want to add a method for that? if it is ok to get it just from the getAll methods so don't add one

2017-01-17 12:35 UTC, meytal127 commented on src/metrics.js
> +function resetCustomMetersMetrics() {
done

2017-01-17 12:36 UTC, meytal127 commented on src/metrics.js
> +module.exports.customMeterMetric = function (metricName) {
done

2017-01-17 12:36 UTC, meytal127 commented on src/metrics.js
> +var customMetersMetrics = new Set();
It might be nice, I will open an issue on it.

2017-01-18 15:24 UTC, merged